version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  commands:
    - python3 -m pip install -U pip
    - python3 -m pip install -U tox
    - tox -e docs
    - mkdir --parents $READTHEDOCS_OUTPUT/html/
    - cp --recursive docs/* $READTHEDOCS_OUTPUT/html/

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf

python:
  install:
    - method: pip
      path: .
