services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "$$MYSQL_PORT",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      timeout: 5s
      retries: 2
    networks:
      - pdextras
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_DB=${MYSQL_DBNAME}
    ports:
      - ${POSTGRESQL_PORT}:${POSTGRESQL_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRESQL_USER"]
      interval: 5s
      timeout: 5s
      retries: 2
    networks:
      - pdextras
  python:
    build: ./
    environment:
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}

    depends_on:
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - pdextras
networks:
  pdextras:
