name: Tox Build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    env:
      MYSQL_HOST: ${{ env.MYSQL_HOST }}
      MYSQL_USER: ${{ env.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
      MYSQL_PORT: ${{ env.MYSQL_PORT }}
      POSTGRESQL_HOST: ${{ env.POSTGRESQL_HOST }}
      POSTGRESQL_USER: ${{ env.POSTGRESQL_USER }}
      POSTGRESQL_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
      POSTGRESQL_PORT: ${{ env.POSTGRESQL_PORT }}
      SQLSERVER_HOST: ${{ env.SQLSERVER_HOST }}
      SQLSERVER_USER: ${{ env.SQLSERVER_USER }}
      SQLSERVER_PASSWORD: ${{ env.SQLSERVER_PASSWORD }}
      SQLSERVER_PORT: ${{ env.SQLSERVER_PORT }}
      MONGO_HOST: ${{ env.MONGO_HOST }}
      MONGO_USER: ${{ env.MONGO_USER }}
      MONGO_PASSWORD: ${{ env.MONGO_PASSWORD }}
      MONGO_PORT: ${{ env.MONGO_PORT }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          env
          python -m pip install -U pip
          python -m pip install -U tox tox-gh-actions
      - name: Test with tox
        run: tox
